chainId: 1
nodeEndpoint: "https://rpc.flashbots.net/fast"
gasPriceEndpoint: "https://gas-api.metaswap.codefi.network/networks/1"
swapRouter: 0xE592427A0AEce92De3Edee1F18E0157C05861564
tokenIn: "" # WETH
tokenOut: "" # Goodle
poolFee: 10000
recipient: ""
amountIn: 0.0045
