chainId: 42161
nodeEndpoint: ""
gasPriceEndpoint: "https://gas-api.metaswap.codefi.network/networks/42161"
gasTipMultiplier: 1.0
swapRouter: 0x68b3465833fb72A70ecDF485E0e4C7bD8665Fc45 # swapRouter02 contract
tokenIn: "0x82aF49447D8a07e3bd95BD0d56f35241523fBab1" # WETH
tokenOut: "0xDA10009cBd5D07dd0CeCc66161FC93D7c9000da1" # DAI
poolFee: 500
recipient: ""
amountIn: 0.00001
isNative: true
minDestAmount: 0
leftoverMaxPercent: 0.15 #15% based on amountIn
leftoverMinPercent: 0.001 #0.1% based on amountIn
