chainId: 1
nodeEndpoint: "https://eth.llamarpc.com"
gasPriceEndpoint: "https://gas-api.metaswap.codefi.network/networks/1"
gasTipMultiplier: 1.0
swapRouter: 0xE592427A0AEce92De3Edee1F18E0157C05861564
tokenIn: "0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2" # WETH
tokenOut: "0xdac17f958d2ee523a2206206994597c13d831ec7" # USDT
poolFee: 100
recipient: ""
amountIn: 0.00001
isNative: true
leftoverMaxPercent: 0.15 #15% based on amountIn
leftoverMinPercent: 0.001 #0.1% based on amountIn
maxTry: 10
